import 'dart:convert';
import 'dart:ffi';
import 'dart:math';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:octopus/pb/msg.pb.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:window_manager/window_manager.dart';

import 'event/event.dart';
import 'main.dart';
import 'native_notify.dart';
import 'package:fixnum/fixnum.dart' as $fixnum;
import 'package:path/path.dart' as path;

class LoginData {
  String nickname = "";
  String password = "";
}

class Data {
  static EventList onLogin = EventList();
  static EventList onLogout = EventList();

  static LoginData loginData = LoginData();
  static Autogenerated data = Autogenerated();
  static String _server = "";
  static String get server => _server;
  static set server(String v) {
    _server = v;
    save();
  }

  static save() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setString("server", _server);
  }

  static void setUP(String nickname, String password) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setString("nickname", nickname);
    prefs.setString("password", password);

    loginData.nickname = nickname;
    loginData.password = password;
  }

  static Future<void> init(fn) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String? svr = prefs.getString("server");

    if (svr == null || svr == "") {
      svr = "127.0.0.1:7457";
    }

    server = svr;

    String? nickname = prefs.getString("nickname");
    String? password = prefs.getString("password");
    if (nickname != null) {
      loginData.nickname = nickname;
    }

    if (password != null) {
      loginData.password = password;
    }

    fn();
  }
}

// https://javiercbk.github.io/json_to_dart/
class Autogenerated {
  ScrollController pageScrollerController = ScrollController();
  ScrollController friendsScrollerController = ScrollController();

  User me = User();
  List<User> friends = [];

  Map<int, List<Message>> messages = {};

  Autogenerated();

  EventList chatTargetEvent = EventList();
  EventList friendListEvent = EventList();
  EventList msgCurrentEvent = EventList();

  init(OnLogin d) {
    friends.clear();
    messages.clear();
    me._d = d.me;
    for (var i = 0; i < d.friends.length; i++) {
      var u = User();
      u._d = d.friends[i];
      u._online = u._d.online;
      friends.add(u);
    }
    friendListEvent.emit();
  }

  User _chatTarget = User();
  User get chatTarget => _chatTarget;
  set chatTarget(User value) {
    if (_chatTarget != null) {
      _chatTarget.iscurrent = false;
    }
    _chatTarget = value;
    _chatTarget.unread = 0;
    _chatTarget.iscurrent = true;
    chatTargetEvent.emit();
    if (pageScrollerController.hasClients) {
      animateScroller(pageScrollerController);
    }
  }

  setUserOffline(int uid) {
    for (var element in friends) {
      if (element.iD == uid) {
        element.online = false;
      }
    }
  }

  User getUser(int uid) {
    for (var element in friends) {
      if (element.iD == uid) {
        return element;
      }
    }
    return me;
  }

  setUserOnline(Friend f) {
    bool check = false;
    for (var element in friends) {
      if (element.iD == f.iD.toInt()) {
        check = true;
        element.online = true;
      }
    }
    if (!check) {
      f.online = true;
      User u = User();
      u._d = f;
      friends.add(u);
      friendListEvent.emit();
    }
  }

  List<Message> getMessage(int target) {
    List<Message>? list = messages[target];
    if (list == null) {
      list = [];
      messages[target.toInt()] = list;
    }
    return list;
  }

  setMsgSended(OnUploadReq one) {
    List<Message> list;

    if (one.from == me.iD) {
      return;
    } else {
      list = getMessage(one.from.toInt());
    }

    var msg = list.firstWhere((element) => element._d.iD == one.iD);
    msg.sended = true;
  }

  Message addMessage(Msg one) {
    List<Message> list;

    if (one.from == me.iD) {
      list = getMessage(one.to.toInt());
    } else {
      list = getMessage(one.from.toInt());
    }

    var msg = Message(one);
    list.add(msg);

    bool shouldEmit = false;

    if (one.from != me.iD) {
      var checkid = one.from.toInt();
      var index = friends.indexWhere((element) => element.iD == checkid);
      var user = friends.removeAt(index);
      friends.insert(0, user);
      shouldEmit = true;
      friendListEvent.emit();
      animateScrollerTop(friendsScrollerController);
    }

    if (one.from == chatTarget.iD || one.from == me.iD) {
      shouldEmit = true;
      animateScroller(pageScrollerController);
    } else {
      for (var element in friends) {
        if (element.iD == one.from) {
          element.unread++;
        }
      }
    }

    if (shouldEmit) {
      msgCurrentEvent.emit();
    }

    notify(one);
    return msg;
  }

  notify(Msg one) async {
    if (!await windowManager.isFocused()) {
      User user = Data.data.getUser(one.from.toInt());
      NativeNotify.show(user.nickname, "发来一条消息");
    }
  }

  animateScrollerTop(ScrollController controller) {
    Future.delayed(const Duration(milliseconds: 100), () {
      controller.jumpTo(
        controller.position.minScrollExtent,
        // curve: Curves.easeOut, //动画效果
        // duration: const Duration(milliseconds: 100),
      );
    });
  }

  animateScroller(ScrollController controller) {
    Future.delayed(const Duration(milliseconds: 100), () {
      controller.jumpTo(
        controller.position.maxScrollExtent,
        // curve: Curves.easeOut, //动画效果
        // duration: const Duration(milliseconds: 100),
      );
    });
  }
}

class Message extends EventList {
  Msg _d = Msg();

  Message(Msg one) {
    _d = one;
  }

  int get from => _d.from.toInt();
  int get sender => _d.sender.toInt();
  int get to => _d.to.toInt();
  String get id => _d.iD;

  String get type {
    if (_d.hasFile()) {
      return "file";
    }
    if (_d.hasText()) {
      return "text";
    }

    return "image";
  }

  String savepath = "";

  String get filename {
    if (_d.hasImage()) {
      return _d.image.fileName;
    }
    return _d.file.fileName;
  }

  String get content {
    return _d.text.text;
  }

  String get url {
    var ext = path.extension(filename).toLowerCase();
    return _d.iD + ext;
  }

  bool _sended = false;
  bool get sended => _sended;
  set sended(bool value) {
    _sended = value;
    emit();
  }

  double _progress = 0;
  double get progress => _progress;
  set progress(double value) {
    _progress = value;
    emit();
  }

  bool _downloading = false;
  bool get downloading => _downloading;
  set downloading(bool value) {
    _downloading = value;
    emit();
  }
}

class User extends EventList {
  Friend _d = Friend();
  int get iD => _d.iD.toInt();
  String get nickname => _d.nickname;
  String get avatar => _d.avatar;

  bool _current = false;
  bool get iscurrent => _current;
  set iscurrent(bool value) {
    _current = value;
    emit();
  }

  bool _online = false;
  bool get online => _online;
  set online(bool value) {
    _online = value;
    emit();
  }

  int _unread = 0;
  int get unread => _unread;
  set unread(int value) {
    _unread = value;
    emit();
  }

  bool group = false;
}
