import 'dart:convert';

import 'package:flutter/material.dart';

import 'event/event.dart';

class Data {
  static Autogenerated data = Autogenerated();
}

// https://javiercbk.github.io/json_to_dart/
class Autogenerated extends EventList {
  User me = User();
  List<User> friends = [];

  Map<int, List<Message>> messages = {};

  Autogenerated();

  int _chatTarget = 0;
  int get chatTarget => _chatTarget;
  set chatTarget(int value) {
    _chatTarget = value;
    emit();
  }

  List<Message> getMessage(int target) {
    List<Message>? list = messages[target];
    if (list == null) {
      list = [];
      messages[target] = list;
    }
    return list;
  }

  void addMessage(Message msg) {
    var list = getMessage(msg.from);
    msg.content = String.fromCharCodes(base64Decode(msg.content));
    list.add(msg);
    emit();
  }

  Autogenerated.fromJson(Map<String, dynamic> json) {
    me = User.fromJson(json['Me']);
    friends = <User>[];
    json['Friends'].forEach((v) {
      friends.add(User.fromJson(v));
    });
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['Me'] = me.toJson();
    data['Friends'] = friends.map((v) => v.toJson()).toList();
    return data;
  }
}

class Message {
  String type = "";
  int from = 0;
  int to = 0;
  String content = "";
  String url = "";
  String filename = "";

  Message.fromJson(Map<String, dynamic> json) {
    type = json['Type'];
    from = json['From'];
    to = json['To'];
    content = json['Content'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['Type'] = type;
    data['From'] = from;
    data['To'] = to;
    data['Content'] = content;
    return data;
  }
}

class User extends EventList {
  int iD = 0;
  String nickname = "";
  String password = "";
  String avatar = "";
  bool _online = false;
  int _unread = 0;

  bool get online => _online;
  set online(bool value) {
    _online = value;
    emit();
  }

  int get unread => _unread;
  set unread(int value) {
    _unread = value;
    emit();
  }

  User();

  User.fromJson(Map<String, dynamic> json) {
    iD = json['ID'];
    nickname = json['Nickname'];
    password = json['Password'];
    avatar = json['Avatar'];
    _online = json['Online'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['ID'] = iD;
    data['Nickname'] = nickname;
    data['Password'] = password;
    data['Avatar'] = avatar;
    data['Online'] = _online;
    return data;
  }
}
