import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'event/event.dart';

class Data {
  static Autogenerated data = Autogenerated();
  static String _server = "";
  static String get server => _server;
  static set server(String v) {
    _server = v;
    save();
  }

  static save() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setString("server", _server);
  }

  static void setUP(String nickname, String password) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setString("nickname", nickname);
    prefs.setString("password", password);

    data.me.nickname = nickname;
    data.me.password = password;
    data.me.emit();
  }

  static Future<void> init(fn) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String? svr = prefs.getString("server");

    if (svr == null || svr == "") {
      svr = "127.0.0.1:7457";
    }

    server = svr;

    String? nickname = prefs.getString("nickname");
    String? password = prefs.getString("password");
    if (nickname != null) {
      data.me.nickname = nickname;
    }

    if (password != null) {
      data.me.password = password;
    }

    fn();
  }
}

// https://javiercbk.github.io/json_to_dart/
class Autogenerated extends EventList {
  ScrollController pageScrollerController = ScrollController();
  ScrollController friendsScrollerController = ScrollController();

  User me = User();
  List<User> friends = [];

  Map<int, List<Message>> messages = {};

  Autogenerated();

  User _chatTarget = User();
  User get chatTarget => _chatTarget;
  set chatTarget(User value) {
    _chatTarget = value;
    _chatTarget.unread = 0;
    emit();
    animateScroller(pageScrollerController);
  }

  setUserOffline(int uid) {
    for (var element in friends) {
      if (element.iD == uid) {
        element.online = false;
      }
    }
  }

  setUserOnline(User u) {
    bool check = false;
    for (var element in friends) {
      if (element.iD == u.iD) {
        check = true;
        element.online = true;
      }
    }
    if (!check) {
      u.online = true;
      friends.add(u);
      emit();
    }
  }

  List<Message> getMessage(int target) {
    List<Message>? list = messages[target];
    if (list == null) {
      list = [];
      messages[target] = list;
    }
    return list;
  }

  void addMessage(Message msg) {
    List<Message> list;

    if (msg.from == me.iD) {
      list = getMessage(msg.to);
    } else {
      list = getMessage(msg.from);
    }
    var content = base64Decode(msg.content);
    msg.content = utf8.decode(content);
    list.add(msg);

    bool shouldEmit = false;

    if (msg.from != me.iD) {
      var index = friends.indexWhere((element) => element.iD == msg.from);
      var user = friends.removeAt(index);
      friends.insert(0, user);
      shouldEmit = true;
      animateScrollerTop(friendsScrollerController);
    }

    if (msg.from == chatTarget.iD || msg.from == me.iD) {
      shouldEmit = true;
      animateScroller(pageScrollerController);
    } else {
      for (var element in friends) {
        if (element.iD == msg.from) {
          element.unread++;
        }
      }
    }

    if (shouldEmit) {
      emit();
    }
  }

  animateScrollerTop(ScrollController controller) {
    Future.delayed(const Duration(milliseconds: 100), () {
      controller.jumpTo(
        controller.position.minScrollExtent,
        // curve: Curves.easeOut, //动画效果
        // duration: const Duration(milliseconds: 100),
      );
    });
  }

  animateScroller(ScrollController controller) {
    Future.delayed(const Duration(milliseconds: 100), () {
      controller.jumpTo(
        controller.position.maxScrollExtent,
        // curve: Curves.easeOut, //动画效果
        // duration: const Duration(milliseconds: 100),
      );
    });
  }

  fromJson(Map<String, dynamic> json) {
    me.fromJson(json['Me']);
    friends = <User>[];
    json['Friends'].forEach((v) {
      friends.add(User().fromJson(v));
    });
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['Me'] = me.toJson();
    data['Friends'] = friends.map((v) => v.toJson()).toList();
    return data;
  }
}

class Message extends EventList {
  String type = "";
  int from = 0;
  int to = 0;
  String content = "";
  String url = "";
  String filename = "";

  double _progress = 0;
  double get progress => _progress;
  set progress(double value) {
    _progress = value;
    emit();
  }

  bool _downloading = false;
  bool get downloading => _downloading;
  set downloading(bool value) {
    _downloading = value;
    emit();
  }

  Message fromJson(Map<String, dynamic> json) {
    type = json['Type'];
    from = json['From'];
    to = json['To'];
    if (type == "text") {
      content = json['Content'];
    } else {
      url = json["URL"];
      filename = json["FileName"];
    }

    return this;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['Type'] = type;
    data['From'] = from;
    data['To'] = to;
    data['Content'] = content;
    return data;
  }
}

class User extends EventList {
  int iD = 0;
  String nickname = "";
  String password = "";
  String avatar = "";
  bool _online = false;
  int _unread = 0;

  bool get online => _online;
  set online(bool value) {
    _online = value;
    emit();
  }

  int get unread => _unread;
  set unread(int value) {
    _unread = value;
    emit();
  }

  User();

  User fromJson(Map<String, dynamic> json) {
    iD = json['ID'];
    nickname = json['Nickname'];
    password = json['Password'];
    avatar = json['Avatar'];
    _online = json['Online'];
    return this;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['ID'] = iD;
    data['Nickname'] = nickname;
    data['Password'] = password;
    data['Avatar'] = avatar;
    data['Online'] = _online;
    return data;
  }
}
