import 'package:flutter/material.dart';
import 'package:octopus/data.dart';

import 'client.dart';
import 'line_input.dart';

class LoginPage extends StatefulWidget {
  const LoginPage({
    Key? key,
  }) : super(key: key);

  @override
  State<LoginPage> createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  final TextEditingController _usernameController =
      TextEditingController(text: "23274");
  final TextEditingController _passwordController =
      TextEditingController(text: "123");

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('登录'),
          brightness: Brightness.dark,
        ),
        body: Center(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              // _getRoundImage('images/logo.png', 100.0),
              const SizedBox(
                height: 60,
              ),
              LineInput(
                  hint: "账号",
                  icon: Icons.mobile_friendly_rounded,
                  controller: _usernameController),
              LineInput(
                  hint: "密码",
                  icon: Icons.lock,
                  controller: _passwordController),
              const SizedBox(
                height: 10,
              ),
              _getLoginButton(),
            ],
          ),
        ),
        bottomNavigationBar: Row(
          children: [
            TextButton(
              child: Text('设置'),
              onPressed: () {
                showDialog(
                    context: context,
                    builder: (BuildContext context) {
                      var opt = LineInput(
                        hint: '服务器地址',
                        icon: Icons.web,
                      );

                      return AlertDialog(
                        content: opt,
                        actions: <Widget>[
                          TextButton(
                            child: Text('设置'),
                            onPressed: () {
                              print(opt.text);
                              Navigator.of(context).pop();
                            },
                          ),
                        ],
                      );
                    });
              },
            ),
            Expanded(
              flex: 2,
              child: SizedBox.fromSize(),
            ),
            TextButton(
              child: Text('注册'),
              onPressed: () {
                print("object");
              },
            ),
          ],
        ));
  }

  Widget _getRoundImage(String imageName, double size) {
    return Container(
      width: size,
      height: size,
      clipBehavior: Clip.antiAlias,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.all(Radius.circular(size / 2)),
      ),
      child: Image.asset(
        imageName,
        fit: BoxFit.fitWidth,
      ),
    );
  }

  Widget _getLoginButton() {
    return Container(
      height: 50,
      width: double.infinity,
      margin: EdgeInsets.all(10),
      decoration: BoxDecoration(
        color: Theme.of(context).primaryColor,
        borderRadius: BorderRadius.circular(4.0),
      ),
      child: TextButton(
        style: ButtonStyle(
          foregroundColor: MaterialStateProperty.all<Color>(Colors.white),
          backgroundColor:
              MaterialStateProperty.all<Color>(Theme.of(context).primaryColor),
        ),
        child: const Text('登录'),
        onPressed: () {
          Client.instance.login(
              _usernameController.text.trim(), _passwordController.text.trim());
          Client.instance.addHandler("login", (err, data) {
            Data.data = Autogenerated.fromJson(data);
            Navigator.of(context).pushNamed("/chat");
          }, true);
        },
      ),
    );
  }
}
